fixes

diff --git a/bin/stalfos-image-init b/bin/stalfos-image-init
--- a/bin/stalfos-image-init
+++ b/bin/stalfos-image-init
@@ -18,9 +18,6 @@ hooks_prepend() {
     shift
 
     hooks=("$@" "${hooks[@]}")
-    #echo >&2 "debug: exit_hooks=${exit_hooks[@]}"
-    #echo >&2 "debug: error_hooks=${error_hooks[@]}"
-    #exit 1
 }
 
 hooks_run() {
@@ -30,6 +27,13 @@ hooks_run() {
     for cmd in "${hooks[@]}"; do
         "${cmd[@]}"
     done
+}
+
+hook_rm_img() {
+    if [[ -f "$stalfos_img" ]]; then
+        echo >&2 "failure-cleanup: rm $stalfos_img"
+        rm -f -- "$stalfos_img"
+    fi
 }
 
 hook_rm_chroot() {
@@ -57,6 +61,7 @@ die() {
 }
 
 nspawn() {
+    # FIXME: nspawn does not return correct exit code
     sudo systemd-nspawn \
         --directory="$stalfos_img_chroot" \
         --bind="$pacman_cache_dir:/var/cache/pacman" \
@@ -141,7 +146,7 @@ wget --timestamping \
 # Unpack the bootstrap image...
 
 truncate -s "$STALFOS_DISK_SIZE" "$stalfos_img"
-hooks_prepend error "rm -f -- '$stalfos_img'"
+hooks_prepend error hook_rm_img
 mkfs.ext4 -L stalfos "$stalfos_img"
 
 sudo mkdir -- "$stalfos_img_chroot"
@@ -163,18 +168,21 @@ find "$stalfos_top/config/rootfs" -type f -printf '%P\0' \
 | while read -r -d '' x; do
     # TODO: Be smarter about file perms and owner
     sudo install -TD -m644 \
-        "$stalfos_top/config/$x" \
+        "$stalfos_top/config/rootfs/$x" \
         "$stalfos_img_chroot/$x"
 done
 
 # Set root password
-nspawn bash -c "print '%s' "$STALFOS_ROOT_PASSWD" | passwd --stdin"
+if [[ -z "$STALFOS_ROOT_PASSWD" ]]; then
+    die 'STALFOS_ROOT_PASSWD is empty'
+fi
+nspawn bash -c "chpasswd <<<'root:$STALFOS_ROOT_PASSWD'"
 
 # Install pkgs
 pkgs=$(sed 's/#.*//' "$stalfos_img_chroot/etc/pacman.d/stalfos.pkglist")
 nspawn pacman-key --init
 nspawn pacman-key --populate
-nspawn sh -c "pacman -Sy --noconfirm --needed linux $pkglist"
+nspawn sh -c "pacman -Sy --noconfirm --needed linux $pkgs"
 
 # Setup services
 nspawn systemctl set-default multi-user.target
